version: '2'

services:
  webserver:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./build/mysql:/docker-entrypoint-initdb.d
      - ./tmp/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: monitor
      MYSQL_USER: web
      MYSQL_PASSWORD: 1234
  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    restart: always
    ports:
      - 8080:80